const foodItems=[
    {
        "_id":"63cc5cf58201667f6b9cd942",
        "foodName":"Kullad Chai",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"100ml",
        "halfPrice":"15",
        "fullQuant":"250ml",
        "fullPrice":"25",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63cce23e8201667f6b9cd945",
        "foodName":"Kullad Masala Chai",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"100ml",
        "halfPrice":"20",
        "fullQuant":"200ml",
        "fullPrice":"30",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63cce24f8201667f6b9cd947",
        "foodName":"Kullad Adrak Chai",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"100ml",
        "halfPrice":"20",
        "fullQuant":"200ml",
        "fullPrice":"30",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63cce2698201667f6b9cd949",
        "foodName":"Kullad Adrak Elaichi Chai",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"100ml",
        "halfPrice":"25",
        "fullQuant":"200ml",
        "fullPrice":"35",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63cce2768201667f6b9cd94b",
        "foodName":"Kullad Elaichi Chai",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"100ml",
        "halfPrice":"20",
        "fullQuant":"200ml",
        "fullPrice":"30",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
    "_id":"63cce31f8201667f6b9cd94d",
    "foodName":"Lemon Tea",
    "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
    "isHalf":false,
    "halfQaunt":"","halfPrice":
    "",
    "fullQuant":"200ml",
    "fullPrice":"15",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
    "_id":"63cce32b8201667f6b9cd94f",
    "foodName":"Ginger Lemon Tea",
    "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
    "isHalf":false,
    "halfQaunt":"","halfPrice":
    "",
    "fullQuant":"200ml",
    "fullPrice":"15",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
        "_id":"63cce3378201667f6b9cd951",
        "foodName":"Green Tea",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
        "isHalf":false,
        "halfQaunt":"","halfPrice":
        "",
        "fullQuant":"200ml",
        "fullPrice":"25",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
    "_id":"63cce3488201667f6b9cd953",
    "foodName":"Hot Chocolate Tea",
    "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
    "isHalf":false,
    "halfQaunt":"","halfPrice":
    "",
    "fullQuant":"200ml",
    "fullPrice":"65",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
    "_id":"63cce3698201667f6b9cd955",
    "foodName":"Coffee",
    "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdEd6P5I6JgrHU-YTHqjjHVQS6fap-UEPZcA&usqp=CAU",
    "isHalf":true,
    "halfQaunt":"100ml",
    "halfPrice":"30",
    "fullQuant":"200ml",
    "fullPrice":"60",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
    "_id":"63cce3f08201667f6b9cd958",
    "foodName":"Steamed Veg Momo",
    "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/steamMomo_u7nf60.jpg",
    "isHalf":true,
    "halfQaunt":"4",
    "halfPrice":"30",
    "fullQuant":"8",
    "fullPrice":"49",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
    "_id":"63cce4138201667f6b9cd95a",
    "foodName":"Steamed Paneer Momo",
    "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/steamMomo_u7nf60.jpg",
    "isHalf":true,
    "halfQaunt":"4",
    "halfPrice":"50",
    "fullQuant":"8",
    "fullPrice":"80",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
    "_id":"63cce4288201667f6b9cd95c",
    "foodName":"Steamed Chicken Momo",
    "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/steamMomo_u7nf60.jpg",
    "isHalf":true,
    "halfQaunt":"4",
    "halfPrice":"40",
    "fullQuant":"8",
    "fullPrice":"70",
    "isAddon":false,
    "nameAddon":"",
    "priceAddon":"",
    "__v":0},

    {
        "_id":"63ccea738201667f6b9cd960",
        "foodName":"Deep Fried Veg Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816913/foodImg/friedMomo_dokli0.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"40",
        "fullQuant":"8",
        "fullPrice":"60",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf83d8201667f6b9cd963",
        "foodName":"Deep Fried Paneer Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816913/foodImg/friedMomo_dokli0.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"60",
        "fullQuant":"8",
        "fullPrice":"90",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf8548201667f6b9cd965",
        "foodName":"Deep Fried Chicken Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816913/foodImg/friedMomo_dokli0.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"50",
        "fullQuant":"8",
        "fullPrice":"80",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf8af8201667f6b9cd967",
        "foodName":"Kurkure Veg Momo",
        "foodImg":"https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bovaozfntudokwydunwk",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"60",
        "fullQuant":"8",
        "fullPrice":"90",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf8d68201667f6b9cd969",
        "foodName":"Kurkure Paneer Momo",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOrCqB2U_x_a7vCI5e_ozJ1SpywBSjoOT-Yw&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"70",
        "fullQuant":"8",
        "fullPrice":"99",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf9088201667f6b9cd96b",
        "foodName":"Kurkure Chicken Momo",
        "foodImg":"https://lh3.googleusercontent.com/ZTaQbXGPCnLXxEABPRYfMcEGa4V2eJvvH5XDFpf6mnU3q3HQw9vl7o47hJLQ64d8bzYgeEXKltiWSqD5Y7I_ngWKML3zawiFpNdm3vIUFA=w512-rw",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"70",
        "fullQuant":"8",
        "fullPrice":"99",
        "isAddon":true,
        "nameAddon":"Peri Peri",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccf9718201667f6b9cd96e",
        "foodName":"Kothey Veg Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/kotheMomo_dy1gj5.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"60",
        "fullQuant":"8",
        "fullPrice":"80",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccf98e8201667f6b9cd970",
        "foodName":"Kothey Paneer Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/kotheMomo_dy1gj5.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"70",
        "fullQuant":"8",
        "fullPrice":"99",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccf9998201667f6b9cd972",
        "foodName":"Kothey Chicken Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/kotheMomo_dy1gj5.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"70",
        "fullQuant":"8",
        "fullPrice":"99",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccf9f98201667f6b9cd974",
        "foodName":"Chilli Veg Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/chilliMomo_vaagbb.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"60",
        "fullQuant":"8",
        "fullPrice":"99",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccfa088201667f6b9cd976",
        "foodName":"Chilli Paneer Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/chilliMomo_vaagbb.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"80",
        "fullQuant":"8",
        "fullPrice":"120",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63ccfa108201667f6b9cd978",
        "foodName":"Chilli Chicken Momo",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/chilliMomo_vaagbb.jpg",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"80",
        "fullQuant":"8",
        "fullPrice":"120",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63ccfa638201667f6b9cd97a",
        "foodName":"Paper Cup Tea",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816911/foodImg/papercupTea_vdjslb.webp",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"100ml",
        "fullPrice":"10",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63ccfad88201667f6b9cd97c",
        "foodName":"Plain Maggi",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/plainMaggie_gi6geu.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"30",
        "isAddon":true,
        "nameAddon":"Egg",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccfaf18201667f6b9cd97e",
        "foodName":"Masala Maggi",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816911/foodImg/masalaMaggie_dt05v5.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"60",
        "isAddon":true,
        "nameAddon":"Egg",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccfb368201667f6b9cd980",
        "foodName":"Khao Noodles",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816913/foodImg/khaoNoodles_ev6cxh.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"30",
        "isAddon":true,
        "nameAddon":"Egg",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccfb638201667f6b9cd982",
        "foodName":"Butter Maggi",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/butterMaggie_qpf0qk.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"45",
        "isAddon":true,
        "nameAddon":"Egg",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccfb818201667f6b9cd984",
        "foodName":"Cheese Maggi",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/cheeseMaggie_r8iom3.webp",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"69",
        "isAddon":true,
        "nameAddon":"Egg",
        "priceAddon":
        "20","__v":0
    },
    {
        "_id":"63ccfba18201667f6b9cd986",
        "foodName":"Sunny Side up",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/sunnySideUp_l2aznb.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"59",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccfbc98201667f6b9cd988",
        "foodName":"Bun Maska",
        "foodImg":"https://res.cloudinary.com/dlg8hsnud/image/upload/v1674816912/foodImg/bunMaska_ivpffy.jpg",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"30",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63ccfbe88201667f6b9cd98a",
        "foodName":"Chicken Momo Stew",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6iZdd15F2--RGaOBzekH8c1B8eHZiXMgeAQ&usqp=CAU",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"30",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },

    {
        "_id":"63ccfc068201667f6b9cd98c",
        "foodName":"French Fries",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6iZdd15F2--RGaOBzekH8c1B8eHZiXMgeAQ&usqp=CAU",
        "isHalf":false,
        "halfQaunt":"",
        "halfPrice":"",
        "fullQuant":"1",
        "fullPrice":"59",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    },
    {
        "_id":"63ccfc2b8201667f6b9cd98e",
        "foodName":"Spring Roll",
        "foodImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6iZdd15F2--RGaOBzekH8c1B8eHZiXMgeAQ&usqp=CAU",
        "isHalf":true,
        "halfQaunt":"4",
        "halfPrice":"89",
        "fullQuant":"6",
        "fullPrice":"99",
        "isAddon":false,
        "nameAddon":"",
        "priceAddon":"",
        "__v":0
    }
]
export default foodItems